services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    working_dir: /app  # Set the working directory
    stdin_open: true  # Keep STDIN open for interactive sessions
    tty: true  # Allocate a pseudo-TTY