services:
  css-dev:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: >
      bash -c "sass --watch --poll ./scss:./css & browser-sync start --server --files 'css/*.css, *.html'"
